// frontend/src/features/blog/BlogPostView.vue
<script setup lang="ts">
import { AiCompanion } from '@/features/ai';
import { TwikooComments } from '@/components';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components';
import { DelIcon, EditIcon } from '@/components';
import { Eye, Heart } from '@lucide/vue';
import { blogGateway } from '@/features/blog/api/blogGateway';
import { useAuthStore } from '@/features/auth';
import { useOrigin } from '@/composables';
import { useNotificationStore } from '@/stores';
import type { Post } from '@/features/blog/types';
import { formatDate } from '@/lib/dayjs';
import { useHead } from '@vueuse/head';
import hljs from 'highlight.js/lib/common';
import 'highlight.js/scss/rainbow.scss';
import { marked } from 'marked';
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const route = useRoute();
const router = useRouter();
const postId = ref<string>(route.params.id as string);

const post = ref<Post | null>(null);
const isLoading = ref(false);
const errorMessage = ref('');

// 点赞：一次性表态。服务端不做重复判定（匿名），
// 故「是否已赞」由 localStorage 在客户端持久化，避免重复提交。
const isLiked = ref(false);
const likesCount = ref(0);
const isLiking = ref(false);
const LIKED_KEY = (id: string) => `readinglist:liked:${id}`;

const auth = useAuthStore();
const showEditButton = computed(() => !!auth.user?.is_admin);

const fetchPost = async () => {
  if (!postId.value) {
    errorMessage.value = '无效的文章 ID';
    return;
  }

  isLoading.value = true;
  errorMessage.value = '';

  try {
    const res = await blogGateway.getLegacyPost(postId.value);
    post.value = res as unknown as Post;

    likesCount.value = (res as unknown as Post).likes ?? 0;
    isLiked.value = localStorage.getItem(LIKED_KEY(postId.value)) === '1';
  } catch (err: unknown) {
    console.error(err);
    errorMessage.value =
      err instanceof Error ? err.message : '加载文章失败，请稍后重试。';
    useNotificationStore().error(errorMessage.value);
  } finally {
    isLoading.value = false;
  }
};

const handleRetry = () => {
  fetchPost();
};

// 点赞：乐观反馈 + 服务端确认。先禁、再请求，成功后以返回的最新数为准。
// 失败则回滚并提示，用户可重试。
const handleLike = async () => {
  if (!postId.value || isLiked.value || isLiking.value) return;

  isLiking.value = true;
  try {
    const likes = await blogGateway.likePost(postId.value);
    likesCount.value = likes;
    isLiked.value = true;
    localStorage.setItem(LIKED_KEY(postId.value), '1');
    useNotificationStore().success('已标记为喜欢');
  } catch (err: unknown) {
    console.error(err);
    const msg = err instanceof Error ? err.message : '操作失败，请稍后重试';
    useNotificationStore().error(msg);
  } finally {
    isLiking.value = false;
  }
};

// 阅读统计：剥离 markdown 标记后，分别计中文字符与西文词数，
// 按 400 字/分钟（中文）+ 200 词/分钟（西文）估算阅读时长。
// 不编造指标——无正文时返回 1 分钟 / 0 字。
function readingStats(body: string): { minutes: number; count: number } {
  if (!body) return { minutes: 1, count: 0 };
  const plain = body
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`[^`]*`/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/[#>*_~]/g, ' ')
    .replace(/\s+/g, ' ');
  const cjk = (plain.match(/[一-鿿]/g) || []).length;
  const words = (plain.replace(/[一-鿿]/g, ' ').match(/[A-Za-z0-9]+/g) || [])
    .length;
  const count = cjk + words;
  const minutes = Math.max(1, Math.round(cjk / 400 + words / 200));
  return { minutes, count };
}

const stats = computed(() => readingStats(post.value?.body || ''));

// 更新时间仅在与创建时间不同时才展示，避免噪音
const hasUpdate = computed(
  () =>
    !!post.value?.updated_at &&
    !!post.value?.created_at &&
    post.value.updated_at !== post.value.created_at,
);

// 顶部阅读进度条：跟随窗口滚动
const readProgress = ref(0);
const updateProgress = () => {
  const el = document.documentElement;
  const max = el.scrollHeight - el.clientHeight;
  readProgress.value = max > 0 ? Math.min(1, el.scrollTop / max) : 0;
};

const handleCopyLink = () => {
  navigator.clipboard
    .writeText(window.location.href)
    .then(() => useNotificationStore().success('链接已复制'))
    .catch(() => useNotificationStore().error('复制失败'));
};

onMounted(() => {
  fetchPost();
  window.addEventListener('scroll', updateProgress, { passive: true });
  window.addEventListener('resize', updateProgress);
  updateProgress();
});

watch(
  () => route.params.id,
  (newId): void => {
    if (newId && newId !== postId.value) {
      postId.value = newId as string;
      fetchPost();
    }
  },
);

watch(
  () => post.value?.body,
  async (html): Promise<void> => {
    if (!html) return;
    await nextTick();
    hljs.highlightAll();
    setupCodeCopy();
  },
);

const renderedBody = computed(() => {
  if (!post.value?.body) return '';
  return marked.parse(post.value.body, {
    async: false,
    breaks: false,
  }) as string;
});

// 非 http(s) 开头的 src 用 https://api.kanocifer.chat 作为前缀（仅在 https 环境下生效）
const coverSrc = computed(() =>
  post.value?.cover ? useOrigin(post.value.cover) : '',
);

// 渲染正文中所有 <img src="...">，非 http(s) 开头的补上前缀
const renderedBodyWithOrigin = computed(() => {
  if (!renderedBody.value) return '';
  return renderedBody.value.replace(
    /<img\s+([^>]*?)src=["']([^"']+)["']([^>]*)>/gi,
    (match, pre, src, post) => {
      const fixed = useOrigin(src);
      return `<img ${pre}src="${fixed}"${post}>`;
    },
  );
});

useHead(() => {
  const title = post.value
    ? `${post.value.title} - ReadingList`
    : '文章未找到 - ReadingList';
  const desc = post.value
    ? post.value.summary || `阅读 ${post.value.title} 的完整内容`
    : '抱歉，您请求的文章不存在或已被删除';
  const keywords = post.value
    ? [
        post.value.title,
        post.value.author || 'Kurroome',
        post.value.tags?.[0] || '博客',
        '阅读',
        '读书笔记',
        '个人博客',
      ]
        .filter(Boolean)
        .join(', ')
    : '文章未找到, 阅读清单, ReadingList';

  const imageMeta = post.value?.cover
    ? [
        { property: 'og:image', content: post.value.cover },
        { name: 'twitter:image', content: post.value.cover },
      ]
    : [];

  return {
    title,
    meta: [
      { name: 'description', content: desc },
      { name: 'keywords', content: keywords },
      { property: 'og:title', content: post.value?.title ?? '文章未找到' },
      { property: 'og:description', content: desc },
      { property: 'og:type', content: 'article' },
      {
        property: 'og:url',
        content: `https://readinglist.example.com/blog/${postId.value}`,
      },
      {
        property: 'og:article:author',
        content: post.value?.author || 'Kurroome',
      },
      {
        property: 'og:article:published_time',
        content: post.value?.created_at,
      },
      { property: 'og:article:modified_time', content: post.value?.updated_at },
      {
        property: 'og:article:section',
        content: post.value?.tags?.[0] || '博客',
      },
      { name: 'twitter:title', content: post.value?.title ?? '文章未找到' },
      { name: 'twitter:description', content: desc },
      ...imageMeta,
    ],
  };
});

const showDeleteDialog = ref(false);

const confirmDelete = async () => {
  showDeleteDialog.value = false;
  await handleDelete();
};

const handleDelete = async () => {
  try {
    await blogGateway.deleteLegacyPost(postId.value);
    useNotificationStore().success('文章删除成功');
    router.push('/blog');
  } catch (err: unknown) {
    console.error('删除文章失败:', err);
    const errorMsg =
      err instanceof Error ? err.message : '删除文章失败，请稍后重试';
    useNotificationStore().error(errorMsg);
  }
};

let clickHandler: ((event: Event) => void) | undefined;
const setupCodeCopy = () => {
  const contentContainer = document.querySelector('.prose');
  if (!contentContainer) return;

  // Early return: buttons already present — skip re-appending on body re-render
  if (contentContainer.querySelector('.copy-btn')) return;

  if (clickHandler) {
    contentContainer.removeEventListener('click', clickHandler);
  }

  clickHandler = (event: Event) => {
    const target = event.target as HTMLElement;
    if (target.classList.contains('copy-btn')) {
      const codeBlock = target.closest('pre');
      if (codeBlock) {
        const codeElement = codeBlock.querySelector('code');
        if (codeElement) {
          navigator.clipboard
            .writeText(codeElement.textContent ?? '')
            .then(() => {
              useNotificationStore().success('代码已复制到剪贴板');
            })
            .catch(() => {
              useNotificationStore().error('复制失败，请手动复制');
            });
        }
      }
    }
  };

  contentContainer.addEventListener('click', clickHandler);

  contentContainer.querySelectorAll('.copy-btn').forEach((btn) => btn.remove());

  const codeBlocks = contentContainer.querySelectorAll('pre');
  codeBlocks.forEach((block) => {
    block.classList.add('w-full', 'whitespace-pre-wrap');
    const button = document.createElement('button');
    button.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-copy-icon lucide-copy"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>`;
    button.className =
      'copy-btn absolute top-1 w-fit right-3 rounded-lg bg-secondary/90 p-1 text-ink';
    block.style.position = 'relative';
    block.appendChild(button);
  });
};

onUnmounted(() => {
  const contentContainer = document.querySelector('.prose');
  if (contentContainer && clickHandler) {
    contentContainer.removeEventListener('click', clickHandler);
  }
  window.removeEventListener('scroll', updateProgress);
  window.removeEventListener('resize', updateProgress);
});
</script>

<template>
  <div class="blog-post bg-page">
    <!-- 阅读进度条：跟随窗口滚动 -->
    <div
      class="bg-border/50 fixed inset-x-0 top-0 z-30 h-[2px] overflow-hidden"
      aria-hidden="true"
    >
      <div
        class="bg-accent h-full origin-left transition-[width] duration-150 ease-out will-change-[width]"
        :style="{ width: `${readProgress * 100}%` }"
      ></div>
    </div>

    <!-- 极简返回条：替代旧 Scroll 指示器，回随笔录 -->
    <div class="mx-auto max-w-[42rem] px-6 pt-10 sm:pt-14">
      <router-link
        to="/blog"
        class="text-muted hover:text-ink group inline-flex items-center gap-1.5 text-[13px] font-medium tracking-wide transition-colors"
      >
        <span
          class="transition-transform duration-200 group-hover:-translate-x-0.5"
          >←</span
        >
        随笔录
      </router-link>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="mx-auto max-w-[42rem] px-6 py-16">
      <div class="bg-surface/70 skeleton-pulse mb-8 h-5 w-20 rounded" />
      <div class="bg-surface/70 skeleton-pulse mb-4 h-9 w-4/5 rounded" />
      <div class="bg-surface/70 skeleton-pulse mb-12 h-4 w-2/5 rounded" />
      <div
        class="bg-surface/70 skeleton-pulse aspect-[16/9] w-full rounded-xl"
      />
      <div class="mt-10 space-y-4">
        <div class="bg-surface/70 skeleton-pulse h-4 w-full rounded" />
        <div class="bg-surface/70 skeleton-pulse h-4 w-full rounded" />
        <div class="bg-surface/70 skeleton-pulse h-4 w-5/6 rounded" />
        <div class="bg-surface/70 skeleton-pulse h-4 w-full rounded" />
      </div>
    </div>

    <!-- Error -->
    <div
      v-else-if="errorMessage"
      class="mx-auto h-screen max-w-[42rem] px-6 py-24"
    >
      <div
        class="border-destructive/30 bg-destructive/5 flex flex-col items-center justify-center rounded-2xl border border-dashed py-16 text-center"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="text-destructive mb-4 h-12 w-12"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
          />
        </svg>
        <p class="text-destructive text-lg font-medium">加载失败</p>
        <p class="text-muted mt-1 text-sm">{{ errorMessage }}</p>
        <button
          @click="handleRetry"
          class="bg-destructive/90 hover:bg-destructive mt-4 cursor-pointer rounded-lg px-4 py-2 text-sm font-medium text-white transition-all duration-150 active:scale-[0.96]"
        >
          重试
        </button>
      </div>
    </div>

    <!-- Article -->
    <article
      v-else-if="post"
      class="mx-auto max-w-[42rem] px-6 pt-8 pb-20 sm:pt-10"
    >
      <!-- 管理员操作 -->
      <div
        v-if="showEditButton"
        class="mb-8 flex items-center justify-end gap-2"
      >
        <router-link
          :to="`/blog/${post._id}/edit`"
          class="bg-surface text-ink hover:bg-surface/80 inline-flex cursor-pointer items-center gap-2 rounded-lg px-3.5 py-1.5 text-[13px] font-medium transition-all duration-150 active:scale-[0.96]"
        >
          <EditIcon />
          编辑
        </router-link>
        <button
          @click="showDeleteDialog = true"
          class="bg-destructive/10 text-destructive hover:bg-destructive/15 inline-flex cursor-pointer items-center gap-2 rounded-lg px-3.5 py-1.5 text-[13px] font-medium transition-all duration-150 active:scale-[0.96]"
        >
          <DelIcon />
          删除
        </button>
      </div>

      <!-- 封面置顶：主视觉先行 -->
      <figure v-if="post.cover" class="mb-10 overflow-hidden rounded-xl">
        <div class="bg-surface aspect-[16/9] w-full overflow-hidden">
          <img
            :src="coverSrc"
            :alt="`${post.title} 封面`"
            class="h-full w-full object-cover"
            loading="lazy"
            style="
              box-shadow: inset 0 0 0 1px oklch(from var(--ink) l c h / 0.08);
            "
          />
        </div>
        <figcaption class="text-muted mt-2.5 text-[11px] tracking-[0.04em]">
          封面 · {{ post.tags?.[0] || 'ReadingList' }}
        </figcaption>
      </figure>

      <!-- 文章头：刊号带 → 眉标 → 大标题 → deck → byline -->
      <header class="mb-12">
        <!-- 刊号式元信息带：出版物气质，mono 大字距 -->
        <div
          class="text-muted mb-6 flex items-center justify-between border-b pb-3 font-mono text-[10px] tracking-[0.18em] uppercase"
        >
          <span>Vol · 随笔录</span>
          <span class="text-muted/70"
            >No · {{ post._id?.slice(-6) || '——' }}</span
          >
        </div>

        <!-- Eyebrow / kicker — accent 唯一一次正式出场 -->
        <div
          class="text-ink mb-5 flex items-center gap-2 text-[11px] font-semibold tracking-[0.14em] uppercase"
        >
          <span class="bg-accent h-px w-5"></span>
          {{ post.tags?.[0] || '未分类' }}
        </div>

        <h1
          class="text-ink font-serif text-[clamp(1.875rem,5vw,2.5rem)] leading-[1.18] font-medium tracking-[-0.02em] text-balance"
        >
          {{ post.title }}
        </h1>

        <!-- Deck / standfirst — 阅读时长 + 字数 + 阅读量 + 可点击喜欢 -->
        <p
          class="text-muted mt-5 text-[15px] leading-relaxed tracking-[0.01em] tabular-nums"
        >
          约 {{ stats.minutes }} 分钟阅读 ·
          {{ stats.count.toLocaleString() }} 字
          <span
            v-if="post.views != null"
            class="inline-flex items-center gap-1"
          >
            · <Eye class="h-3.5 w-3.5" /> {{ post.views }}
          </span>
          <span v-if="post.likes != null" class="inline-flex items-center">
            ·
            <button
              type="button"
              :aria-label="
                isLiked
                  ? `已喜欢 · 当前 ${likesCount}`
                  : `喜欢 · 当前 ${likesCount}`
              "
              :disabled="isLiked || isLiking"
              class="inline-flex cursor-pointer items-center gap-1 rounded transition-colors duration-150 active:scale-[0.96] disabled:cursor-default"
              :class="isLiked ? 'text-ink' : 'text-muted hover:text-ink'"
              @click="handleLike"
            >
              <Heart
                class="h-3.5 w-3.5 transition-all duration-150"
                :class="isLiked ? 'fill-accent' : ''"
              />
              {{ likesCount }}
            </button>
          </span>
        </p>

        <!-- Byline / dateline -->
        <div
          class="text-muted mt-4 flex flex-wrap items-center gap-x-3 gap-y-1.5 text-[13px] tracking-[0.02em]"
        >
          <span v-if="post.author" class="text-ink/80 font-medium">
            {{ post.author }}
          </span>
          <span
            v-if="post.author && post.created_at"
            class="bg-border h-3 w-px"
          ></span>
          <time v-if="post.created_at" :datetime="post.created_at">
            {{ formatDate(post.created_at) }}
          </time>
          <template v-if="hasUpdate">
            <span class="bg-border h-3 w-px"></span>
            <span>更新于 {{ formatDate(post.updated_at) }}</span>
          </template>
        </div>
      </header>

      <!-- 正文 -->
      <div class="prose prose-lg max-w-none">
        <AiCompanion :title="post.title" :content="post.body || ''" />
        <div
          class="prose-body whitespace-pre-wrap"
          v-if="post.body"
          v-html="renderedBodyWithOrigin"
        />
        <div v-else class="text-muted italic">暂无内容</div>
      </div>

      <!-- 文章脚：作者署名块 + 复制链接 -->
      <footer class="mt-14 border-t pt-8">
        <div class="flex flex-wrap items-start justify-between gap-5">
          <div class="flex items-center gap-3.5">
            <span
              class="text-ink ring-border bg-surface flex h-11 w-11 shrink-0 items-center justify-center rounded-full font-serif text-sm font-semibold ring-1"
              >{{ (post.author || 'K').slice(0, 1) }}</span
            >
            <div class="min-w-0">
              <div class="text-ink text-[14px] font-medium tracking-wide">
                {{ post.author || 'Kurroome' }}
              </div>
              <div class="text-muted mt-0.5 text-[12px] tracking-[0.02em]">
                {{
                  hasUpdate
                    ? `最后更新于 ${formatDate(post.updated_at)}`
                    : post.created_at
                      ? `发布于 ${formatDate(post.created_at)}`
                      : ''
                }}
              </div>
            </div>
          </div>
          <button
            type="button"
            @click="handleCopyLink"
            class="text-muted hover:text-ink inline-flex cursor-pointer items-center gap-1.5 text-[12px] font-medium tracking-[0.02em] transition-all duration-150 active:scale-[0.96]"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-3.5 w-3.5"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.8"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
              />
            </svg>
            复制链接
          </button>
        </div>
      </footer>
    </article>

    <TwikooComments
      v-if="post"
      :path="`/blog/${postId}`"
      class="mx-auto max-w-[42rem] px-6 pb-24"
    />

    <Teleport to="body">
      <AlertDialog
        :open="showDeleteDialog"
        @update:open="showDeleteDialog = $event"
      >
        <AlertDialogContent class="sm:max-w-[425px]">
          <AlertDialogHeader>
            <AlertDialogTitle>确认删除这篇文章？</AlertDialogTitle>
            <AlertDialogDescription> 此操作无法撤销。 </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>取消</AlertDialogCancel>
            <AlertDialogAction
              class="bg-destructive hover:bg-destructive/90 text-white"
              @click="confirmDelete"
            >
              删除
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Teleport>
  </div>
</template>

<style>
@import 'twikoo/dist/twikoo.css';

.copy-btn::before {
  content: '复制';
  position: absolute;
  bottom: -150%;
  left: 50%;
  transform: translateX(-50%) translateY(4px);
  opacity: 0;
  transition:
    opacity 0.2s cubic-bezier(0.2, 0, 0, 1),
    transform 0.2s cubic-bezier(0.2, 0, 0, 1);
  padding: 4px 8px;
  background: var(--ink);
  color: var(--page);
  border-radius: var(--radius-sm);
  pointer-events: none;
  font-size: 0.875rem;
  white-space: nowrap;
}

.copy-btn:hover::before {
  opacity: 1;
  transform: translateX(-50%) translateY(0);
}
/* 文章阅读体验由 .prose（base.scss）统一提供。 */

/* —— ① 首段 drop cap：editorial 签名时刻，accent 第 2 次出场 —— */
.prose-body > p:first-of-type::first-letter {
  float: left;
  font-family: ui-serif, Georgia, 'Times New Roman', serif;
  font-size: 3.4em;
  line-height: 0.82;
  font-weight: 600;
  margin: 0.08em 0.12em 0 0;
  color: var(--accent);
}

/* Drop cap rag guard: below 30rem the 3.4em float crushes 1-2 char opening lines */
@media (max-width: 30rem) {
  .prose-body > p:first-of-type::first-letter {
    float: none;
    font-size: 1em;
    font-weight: inherit;
    margin: 0;
    color: inherit;
  }
}

/* —— ④ 章节编号：CSS counter，长文目录感 —— */
.prose-body {
  counter-reset: h2-section;
}
.prose-body h2::before {
  counter-increment: h2-section;
  content: '§ ' counter(h2-section) '  ';
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.62em;
  font-weight: 500;
  letter-spacing: 0.04em;
  color: var(--muted-text);
  vertical-align: 0.18em;
}

/* —— Skeleton pulse —— */
.skeleton-pulse {
  animation: skeleton-pulse 1.8s ease-in-out infinite;
}

.tabular-nums {
  font-variant-numeric: tabular-nums;
}

@keyframes skeleton-pulse {
  0%,
  100% {
    opacity: 0.4;
  }
  50% {
    opacity: 0.7;
  }
}
</style>

// react-app/src/features/blog/BlogPostView.tsx
import type { BlogDetail } from '@/features/blog/api/blogService';
import { blogService } from '@/features/blog/api/blogService';
import { TwikooComments, AiThread } from '@/components';
import { useAuthStore } from '@/features/auth';
import { useNotificationStore } from '@/stores/notificationState';
import { formatDate } from '@/lib/formatdate';
import { useOrigin } from '@/hooks/useOrigin';
import hljs from 'highlight.js/lib/common';
import 'highlight.js/styles/github.css';
import { marked } from 'marked';
import { Eye, Heart } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

function LoadingSkeleton() {
  return (
    <div className="mx-auto max-w-[42rem] px-6 py-16">
      <div className="bg-surface/70 skeleton-pulse mb-8 h-5 w-20 rounded" />
      <div className="bg-surface/70 skeleton-pulse mb-4 h-9 w-4/5 rounded" />
      <div className="bg-surface/70 skeleton-pulse mb-12 h-4 w-2/5 rounded" />
      <div className="bg-surface/70 skeleton-pulse aspect-[16/9] w-full rounded-xl" />
      <div className="mt-10 space-y-4">
        <div className="bg-surface/70 skeleton-pulse h-4 w-full rounded" />
        <div className="bg-surface/70 skeleton-pulse h-4 w-full rounded" />
        <div className="bg-surface/70 skeleton-pulse h-4 w-5/6 rounded" />
        <div className="bg-surface/70 skeleton-pulse h-4 w-full rounded" />
      </div>
    </div>
  );
}

function ErrorState({
  message,
  onRetry,
}: {
  message: string;
  onRetry: () => void;
}) {
  return (
    <div className="border-destructive/30 bg-destructive/5 flex flex-col items-center justify-center rounded-2xl border border-dashed py-16 text-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        className="text-destructive mb-4 h-12 w-12"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth="1.5"
        stroke="currentColor"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
        />
      </svg>
      <p className="text-destructive text-lg font-medium">加载失败</p>
      <p className="text-muted mt-1 text-sm">{message}</p>
      <button
        onClick={onRetry}
        className="bg-destructive/90 hover:bg-destructive mt-4 cursor-pointer rounded-lg px-5 py-2.5 text-sm font-medium text-white transition-all duration-150 active:scale-[0.96]"
      >
        重试
      </button>
    </div>
  );
}

const COPY_ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>`;

function setupCodeCopy(
  container: HTMLElement,
  onCopy: (msg: string) => void,
): () => void {
  const preElements = container.querySelectorAll('pre');
  const cleanups: (() => void)[] = [];

  preElements.forEach((pre) => {
    pre.style.position = 'relative';
    pre.classList.add('group');

    const btn = document.createElement('button');
    btn.innerHTML = COPY_ICON_SVG;
    btn.title = '复制';
    btn.className =
      'absolute top-2 right-2 p-1.5 rounded-md bg-surface/80 text-muted opacity-0 group-hover:opacity-100 transition-opacity duration-200 hover:bg-surface cursor-pointer';
    btn.setAttribute('aria-label', '复制代码');

    const handleClick = () => {
      const code = pre.querySelector('code');
      if (code) {
        navigator.clipboard
          .writeText(code.textContent || '')
          .then(() => onCopy('代码已复制'))
          .catch(() => onCopy('复制失败'));
      }
    };

    btn.addEventListener('click', handleClick);
    pre.appendChild(btn);
    cleanups.push(() => {
      btn.removeEventListener('click', handleClick);
      btn.remove();
    });
  });

  return () => cleanups.forEach((fn) => fn());
}

/**
 * 阅读统计：剥离 markdown 标记后，分别计中文字符与西文词数，
 * 按 400 字/分钟（中文）+ 200 词/分钟（西文）估算阅读时长。
 * 不编造指标——无正文时返回 1 分钟 / 0 字。
 */
function readingStats(body: string): { minutes: number; count: number } {
  if (!body) return { minutes: 1, count: 0 };
  const plain = body
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`[^`]*`/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/[#>*_~]/g, ' ')
    .replace(/\s+/g, ' ');
  const cjk = (plain.match(/[一-鿿]/g) || []).length;
  const words = (plain.replace(/[一-鿿]/g, ' ').match(/[A-Za-z0-9]+/g) || [])
    .length;
  const count = cjk + words;
  const minutes = Math.max(1, Math.round(cjk / 400 + words / 200));
  return { minutes, count };
}

/** 顶部阅读进度条：跟随窗口滚动，scaleX 0→1。 */
function ReadingProgress() {
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    const onScroll = () => {
      const el = document.documentElement;
      const max = el.scrollHeight - el.clientHeight;
      setProgress(max > 0 ? Math.min(1, el.scrollTop / max) : 0);
    };
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    window.addEventListener('resize', onScroll);
    return () => {
      window.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', onScroll);
    };
  }, []);
  return (
    <div className="bg-border/50 fixed inset-x-0 top-0 z-30 h-[2px] overflow-hidden">
      <div
        className="bg-accent h-full origin-left transition-[width] duration-150 ease-out will-change-[width]"
        style={{ width: `${progress * 100}%` }}
      />
    </div>
  );
}

export default function BlogPostView() {
  const { postId } = useParams<{ postId: string }>();
  const navigate = useNavigate();
  const notification = useNotificationStore();
  const { user, isAuthenticated } = useAuthStore();

  const [post, setPost] = useState<BlogDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // 点赞：一次性表态。服务端不做重复判定（匿名），
  // 故「是否已赞」由 localStorage 在客户端持久化，避免重复提交。
  const [isLiked, setIsLiked] = useState(false);
  const [likesCount, setLikesCount] = useState(0);
  const [isLiking, setIsLiking] = useState(false);
  const likedKey = (id: string) => `readinglist:liked:${id}`;

  const showEditButton = isAuthenticated && user?.is_admin;

  // SEO: set document title
  useEffect(() => {
    if (post?.title) {
      document.title = `${post.title} - ReadingList`;
    }
    return () => {
      document.title = 'ReadingList';
    };
  }, [post?.title]);

  // Render markdown to HTML
  const renderedBody = post?.body
    ? (marked.parse(post.body, { async: false, breaks: false }) as string)
    : '';

  // 非 http(s) 开头的 src 用 https://api.kanocifer.chat 作为前缀（仅在 https 环境下生效）
  const coverSrc = post?.cover ? useOrigin(post.cover) : '';

  // 渲染正文中所有 <img src="...">，非 http(s) 开头的补上前缀
  const renderedBodyWithOrigin = renderedBody
    ? renderedBody.replace(
        /<img\s+([^>]*?)src=["']([^"']+)["']([^>]*)>/gi,
        (_match, pre: string, src: string, postAttr: string) =>
          `<img ${pre}src="${useOrigin(src)}"${postAttr}>`,
      )
    : '';

  const stats = post?.body ? readingStats(post.body) : { minutes: 1, count: 0 };
  const hasUpdate =
    !!post?.updated_at &&
    !!post?.created_at &&
    post.updated_at !== post.created_at;

  // Highlight code blocks + setup copy buttons after content renders
  useEffect(() => {
    if (contentRef.current && renderedBody) {
      hljs.highlightAll();
      const cleanup = setupCodeCopy(contentRef.current, (msg) =>
        notification.success(msg),
      );
      return cleanup;
    }
  }, [renderedBody, notification]);

  const fetchPost = useCallback(async () => {
    if (!postId) return;

    setIsLoading(true);
    setError(null);

    try {
      const service = blogService();
      const result = await service.getBlogPost(postId);
      setPost(result);
      setLikesCount(result.likes ?? 0);
      setIsLiked(localStorage.getItem(likedKey(postId)) === '1');
    } catch (err) {
      setError(err instanceof Error ? err.message : '加载文章失败');
    } finally {
      setIsLoading(false);
    }
  }, [postId]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchPost();
  }, [fetchPost]);

  const handleDelete = async () => {
    if (!postId) return;
    setShowDeleteDialog(false);
    try {
      const service = blogService();
      await service.deleteLegacyPost(postId);
      notification.success('文章删除成功');
      navigate('/blog');
    } catch (err) {
      const msg = err instanceof Error ? err.message : '删除文章失败';
      notification.error(msg);
    }
  };

  const handleCopyLink = () => {
    navigator.clipboard
      .writeText(window.location.href)
      .then(() => notification.success('链接已复制'))
      .catch(() => notification.error('复制失败'));
  };

  // 点赞：乐观反馈 + 服务端确认。先禁、再请求，成功后以返回的最新数为准。
  const handleLike = async () => {
    if (!postId || isLiked || isLiking) return;

    setIsLiking(true);
    try {
      const service = blogService();
      const likes = await service.likePost(postId);
      setLikesCount(likes);
      setIsLiked(true);
      localStorage.setItem(likedKey(postId), '1');
      notification.success('已标记为喜欢');
    } catch (err) {
      const msg = err instanceof Error ? err.message : '操作失败，请稍后重试';
      notification.error(msg);
    } finally {
      setIsLiking(false);
    }
  };

  return (
    <div className="bg-page min-h-dvh">
      <ReadingProgress />

      {/* 极简返回条：替代旧 Scroll 指示器，回随笔录 */}
      <div className="mx-auto max-w-[42rem] px-6 pt-10 sm:pt-14">
        <a
          onClick={() => navigate('/blog')}
          className="text-muted hover:text-ink group inline-flex cursor-pointer items-center gap-1.5 text-[13px] font-medium tracking-wide transition-colors"
        >
          <span className="transition-transform duration-200 group-hover:-translate-x-0.5">
            ←
          </span>
          随笔录
        </a>
      </div>

      {isLoading ? (
        <LoadingSkeleton />
      ) : error ? (
        <div className="mx-auto max-w-[42rem] px-6 py-24">
          <ErrorState message={error} onRetry={fetchPost} />
        </div>
      ) : post ? (
        <article className="mx-auto max-w-[42rem] px-6 pt-8 pb-20 sm:pt-10">
          {/* Admin actions — delete only; editor has been removed */}
          {showEditButton && (
            <div className="mb-8 flex items-center justify-end gap-2">
              <button
                onClick={() => setShowDeleteDialog(true)}
                className="bg-destructive/10 text-destructive hover:bg-destructive/15 inline-flex cursor-pointer items-center gap-2 rounded-lg px-3.5 py-1.5 text-[13px] font-medium transition-all duration-150 active:scale-[0.96]"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-3.5 w-3.5"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.5"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
                  />
                </svg>
                删除
              </button>
            </div>
          )}

          {/* 刊号式元信息带：出版物气质，mono 大字距 */}
          <div className="text-muted mb-6 flex items-center justify-between border-b pb-3 font-mono text-[10px] tracking-[0.18em] uppercase">
            <span>Vol · 随笔录</span>
            <span className="text-muted/70">
              No · {post._id?.slice(-6) || '——'}
            </span>
          </div>

          {/* Eyebrow / kicker — first tag (or fallback) */}
          <div className="text-ink mb-5 flex items-center gap-2 text-[11px] font-semibold tracking-[0.14em] uppercase">
            <span className="bg-accent h-px w-5" />
            {post.tags?.[0] || '随笔'}
          </div>

          {/* Headline */}
          <h1 className="text-ink font-serif text-[clamp(1.875rem,5vw,2.5rem)] leading-[1.18] font-medium tracking-[-0.02em] text-balance">
            {post.title}
          </h1>

          {/* Deck — 阅读时长 + 字数 + 阅读量 + 可点击喜欢 */}
          <p className="text-muted mt-5 inline-flex flex-wrap items-center gap-x-1 text-[15px] leading-relaxed tracking-[0.01em] tabular-nums">
            约 {stats.minutes} 分钟阅读 · {stats.count.toLocaleString()} 字
            {post.views != null && (
              <>
                <span className="text-muted/50">·</span>
                <Eye className="h-3.5 w-3.5" />
                <span>{post.views}</span>
              </>
            )}
            {post.likes != null && (
              <>
                <span className="text-muted/50">·</span>
                <button
                  type="button"
                  aria-label={
                    isLiked
                      ? `已喜欢 · 当前 ${likesCount}`
                      : `喜欢 · 当前 ${likesCount}`
                  }
                  disabled={isLiked || isLiking}
                  onClick={handleLike}
                  className={`inline-flex cursor-pointer items-center gap-1 rounded transition-colors duration-150 active:scale-[0.96] disabled:cursor-default ${
                    isLiked ? 'text-ink' : 'text-muted hover:text-ink'
                  }`}
                >
                  <Heart
                    className={`h-3.5 w-3.5 transition-all duration-150 ${
                      isLiked ? 'fill-accent' : ''
                    }`}
                  />
                  <span>{likesCount}</span>
                </button>
              </>
            )}
          </p>

          {/* Byline / dateline */}
          <div className="text-muted mt-4 flex flex-wrap items-center gap-x-3 gap-y-1.5 text-[13px] tracking-[0.02em]">
            {post.author && (
              <span className="text-ink/80 font-medium">{post.author}</span>
            )}
            {post.author && post.created_at && (
              <span className="bg-border h-3 w-px" />
            )}
            {post.created_at && (
              <time dateTime={post.created_at}>
                {formatDate(post.created_at, 'YYYY-MM-DD')}
              </time>
            )}
            {hasUpdate && (
              <>
                <span className="bg-border h-3 w-px" />
                <span>更新于 {formatDate(post.updated_at!, 'YYYY-MM-DD')}</span>
              </>
            )}
          </div>

          {/* 封面置顶：主视觉先行 */}
          {post.cover && (
            <figure className="mt-10 mb-10 overflow-hidden rounded-xl">
              <div className="bg-surface aspect-[16/9] w-full overflow-hidden">
                <img
                  src={coverSrc}
                  alt={`${post.title} 封面`}
                  className="h-full w-full object-cover"
                  loading="lazy"
                  style={{ boxShadow: 'inset 0 0 0 1px rgba(0,0,0,0.08)' }}
                />
              </div>
              <figcaption className="text-muted mt-2.5 text-[11px] tracking-[0.04em]">
                封面 · {post.tags?.[0] || 'ReadingList'}
              </figcaption>
            </figure>
          )}

          {/* 正文 */}
          <div className="prose prose-lg max-w-none">
            <AiThread title={post?.title} content={post?.body || ''} />
            <div ref={contentRef} className="prose-body whitespace-pre-wrap">
              {renderedBodyWithOrigin ? (
                <div
                  dangerouslySetInnerHTML={{
                    __html: renderedBodyWithOrigin,
                  }}
                />
              ) : (
                <p className="text-muted italic">暂无内容</p>
              )}
            </div>
          </div>

          {/* 文章脚：作者署名块 + 复制链接 */}
          <footer className="mt-14 border-t pt-8">
            <div className="flex flex-wrap items-start justify-between gap-5">
              <div className="flex items-center gap-3.5">
                <span className="text-ink ring-border bg-surface flex h-11 w-11 shrink-0 items-center justify-center rounded-full font-serif text-sm font-semibold ring-1">
                  {(post.author || 'K').slice(0, 1)}
                </span>
                <div className="min-w-0">
                  <div className="text-ink text-[14px] font-medium tracking-wide">
                    {post.author || 'Kurroome'}
                  </div>
                  <div className="text-muted mt-0.5 text-[12px] tracking-[0.02em]">
                    {hasUpdate
                      ? `最后更新于 ${formatDate(post.updated_at!, 'YYYY-MM-DD')}`
                      : post.created_at
                        ? `发布于 ${formatDate(post.created_at, 'YYYY-MM-DD')}`
                        : ''}
                  </div>
                </div>
              </div>
              <button
                type="button"
                onClick={handleCopyLink}
                className="text-muted hover:text-ink inline-flex cursor-pointer items-center gap-1.5 text-[12px] font-medium tracking-[0.02em] transition-all duration-150 active:scale-[0.96]"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-3.5 w-3.5"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.8"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
                  />
                </svg>
                复制链接
              </button>
            </div>
          </footer>

          {/* Comments */}
          <div className="mt-10">
            <TwikooComments path={`/blog/${postId}`} />
          </div>
        </article>
      ) : null}

      {/* Delete confirmation dialog */}
      {showDeleteDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div
            className="bg-ink/80 fixed inset-0 backdrop-blur-sm"
            onClick={() => setShowDeleteDialog(false)}
          />
          <div className="bg-page relative w-full max-w-sm rounded-2xl border p-6 shadow-lg">
            <h3 className="text-ink text-lg font-semibold">确认删除</h3>
            <p className="text-muted mt-2 text-sm">
              确定要删除这篇文章吗？此操作无法撤销。
            </p>
            <div className="mt-6 flex justify-end gap-3">
              <button
                onClick={() => setShowDeleteDialog(false)}
                className="bg-surface text-ink hover:bg-surface/80 rounded-xl px-4 py-2.5 text-sm font-medium transition-all duration-150 active:scale-[0.96]"
              >
                取消
              </button>
              <button
                onClick={handleDelete}
                className="bg-destructive hover:bg-destructive/90 rounded-xl px-4 py-2.5 text-sm font-medium text-white transition-all duration-150 active:scale-[0.96]"
              >
                删除
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
